# Generated by Django 5.2.1 on 2025-05-25 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_nota'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nota',
            new_name='NotaAlumnoPorCurso',
        ),
    ]
